### ISSUE TITLE
Add support for gzip compression OTEL_EXPORTER_OTLP_*_COMPRESSION

### ISSUE THREAD

**Issue by arielvalentin** [lightstep/lightstep-developer-satellite#22]
Traces are not processed when sent to the development collector using OTLP HTTP Exporters using gzip compression. 

https://raw.githubusercontent.com/lightstep/lightstep-developer-satellite/master/lightstep-developer-satellite.sh

There are no errors printed however it looks like the developer satellites is pretty old (2020-09-24_05-22-16Z) and likely does not have support for gzip compression: 

```console
[app.go:86 I1218 02:25:58.665219] Satellite release tag: 2020-09-24_05-22-16Z
[app.go:117 I1218 02:25:58.665252] Diagnostics at http://localhost:8000/diagnostics
[server.go:45 I1218 02:25:58.665273] Binding http services to port=8000 secure=false
[app.go:48 I1218 02:25:58.665535] Setting satellite type to: custom
[saas.go:39 I1218 02:25:58.665563] Connecting to LightStep SaaS:api-grpc.lightstep.com:8043
[info.go:77 W1218 02:25:58.665602] unable to find pod labels, this is safe to ignore when running outside of kubernetes environments unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
[selftest.go:25 I1218 02:25:58.665697] Starting Satellite Self-Test...
[selftest.go:168 I1218 02:25:58.892205] Satellite configuration NOT modified by SaaS at startup.
[selftest.go:31 I1218 02:25:58.892241] Satellite Self-Test Results...
```

This is a critical part of the development workflow for me at GitHub. Please consider upgrading the developer satellite to a version that supports compression.

**Comment by arielvalentin** [comment]
@gdvalle follow up question, does it also include a Jaeger Receiver?

My teammate @cjs is testing spicedb, which uses Jaeger by default.

**Comment by gdvalle** [comment]
It should support any ingestion protocol that the regular satellites do, which includes Jaeger over gRPC: https://docs.lightstep.com/docs/use-jaeger-agent-with-lightstep

**Comment by cjs** [comment]
@gdvalle would you mind sharing the exact url that should be used with developer mode and jaeger? I've set my client up using `http://localhost:8360` and have not been able to send traces. When I use an endpoint of `http://localhost:8360/traces/otlp/v0.6` I get a `500` code.

Looking at https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger#WithAgentEndpoint, should we be using the compact Thrift protocol or does the satellite implement the HTTP Thrift collector?

**Comment by gdvalle** [comment]
@cjs I was able to get the [hotrod demo app](https://github.com/jaegertracing/jaeger/tree/main/examples/hotrod) working with jaeger-agent started with `--reporter.grpc.host-port=127.0.0.1:8360 --reporter.grpc.tls.enabled=false`, where host is the dev satellite. I don't think we support the compact Thrift format, but it looks like we support the JSON and binary formats.

**Comment by arielvalentin** [comment]
Yes thank you!
